const MIN_NUMBER_RANGE = 1;
const MAX_NUMBER_RANGE = 9;
const MAX_NUMBER_LENGTH = 3;
const RESTART_TRIGGER = "1";
const QUIT_TRIGGER = "2";

module.exports = {
  MIN_NUMBER_RANGE,
  MAX_NUMBER_RANGE,
  MAX_NUMBER_LENGTH,
  RESTART_TRIGGER,
  QUIT_TRIGGER,
};
