const MIN_NUMBER_RANGE = 1;
const MAX_NUMBER_RANGE = 9;
const MAX_NUMBER_LENGTH = 3;
const RESTART_TRIGGER_NUMBER = 1;
const END_TRIGGER_NUMBER = 2;

module.exports = {
  MIN_NUMBER_RANGE,
  MAX_NUMBER_RANGE,
  MAX_NUMBER_LENGTH,
  RESTART_TRIGGER_NUMBER,
  END_TRIGGER_NUMBER,
};
