const ANSWER_NUMBERS = {
  MIN_NUM: 1,
  MAX_NUM: 9,
};

const ASK_CONTINUE = {
  YES: "1",
  NO: "2",
};

const THREE_TIMES = 3;

const ANSWER_IS_MUST_BE_THREE_LENGTH = 3;

module.exports = { ANSWER_NUMBERS, ASK_CONTINUE, THREE_TIMES, ANSWER_IS_MUST_BE_THREE_LENGTH };
