const GAME_START_MESSAGE = '숫자 야구 게임을 시작합니다.';
const ENTER_USER_NUMBER_MESSAGE = '숫자를 입력해주세요 : ';
const GAME_FINISH_MESSAGE = '3개의 숫자를 모두 맞히셨습니다! 게임 종료';
const NONE_MATCHING_MESSAGE = '낫싱';
const ENTER_GAME_RESART_NUMBER_MESSAGE = '게임을 새로 시작하려면 1, 종료하려면 2를 입력하세요.\n';
const NOT_USER_NUMBER_LENGTH_THREE_ERROR_MESSAGE = '사용자의 입력값은 3자리 수이어야 합니다.';
const INCLUDE_NOT_DIGIT_IN_USER_NUMBER_ERROR_MESSEAGE =
  '사용자의 입력값은 숫자로 이루어져야 합니다.';
const USER_NUMBER_DUPLICATED_ERROR_MESSAGE = '사용자의 입력값은 서로 다른 숫자이어야 합니다.';
const GAME_RESTART_NUMBER_ERROR_MESSAGE = '1 또는 2가 아닌 수가 입력되어 프로그램을 종료합니다.';

module.exports = {
  GUIDE: {
    GAME_START_MESSAGE,
    ENTER_USER_NUMBER_MESSAGE,
    GAME_FINISH_MESSAGE,
    NONE_MATCHING_MESSAGE,
    ENTER_GAME_RESART_NUMBER_MESSAGE,
  },
  ERROR: {
    NOT_USER_NUMBER_LENGTH_THREE_ERROR_MESSAGE,
    INCLUDE_NOT_DIGIT_IN_USER_NUMBER_ERROR_MESSEAGE,
    USER_NUMBER_DUPLICATED_ERROR_MESSAGE,
    GAME_RESTART_NUMBER_ERROR_MESSAGE,
  },
};
